// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['mass.ufl'],
//   'verbosity': 30,
//   'visualise': False}


typedef double ufc_scalar_t;
#include <math.h>
#include <stdalign.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <ufc.h>

// Code for element element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165





ufc_finite_element element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165 =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 1)",
  .cell_shape = tetrahedron,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 4,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 1,

  .needs_transformation_data = 0,
  .interpolation_is_identity = 1,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165

// Code for element element_bdceac99366b2920d64d0754bdb3a21263af46d5

int value_shape_element_bdceac99366b2920d64d0754bdb3a21263af46d5[1] = { 3 };
int reference_value_shape_element_bdceac99366b2920d64d0754bdb3a21263af46d5[1] = { 3 };
ufc_finite_element* sub_elements_element_bdceac99366b2920d64d0754bdb3a21263af46d5[3] = { &element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165, &element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165, &element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165 };

ufc_finite_element element_bdceac99366b2920d64d0754bdb3a21263af46d5 =
{
  .signature = "VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .cell_shape = tetrahedron,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 12,
  .value_rank = 1,
  .value_shape = value_shape_element_bdceac99366b2920d64d0754bdb3a21263af46d5,
  .value_size = 3,
  .reference_value_rank = 1,
  .reference_value_shape = reference_value_shape_element_bdceac99366b2920d64d0754bdb3a21263af46d5,
  .reference_value_size = 3,
  .degree = 1,
  .family = "Lagrange",
  .block_size = 3,

  .needs_transformation_data = 0,
  .interpolation_is_identity = 1,

  .num_sub_elements = 3,
  .sub_elements = sub_elements_element_bdceac99366b2920d64d0754bdb3a21263af46d5
};

// End of code for element element_bdceac99366b2920d64d0754bdb3a21263af46d5

// Code for element element_f550351ae4ab454688402d27a041f1dc22f0a82d





ufc_finite_element element_f550351ae4ab454688402d27a041f1dc22f0a82d =
{
  .signature = "FiniteElement('Lagrange', tetrahedron, 2)",
  .cell_shape = tetrahedron,
  .topological_dimension = 3,
  .geometric_dimension = 3,
  .space_dimension = 10,
  .value_rank = 0,
  .value_shape = NULL,
  .value_size = 1,
  .reference_value_rank = 0,
  .reference_value_shape = NULL,
  .reference_value_size = 1,
  .degree = 2,
  .family = "Lagrange",
  .block_size = 1,

  .needs_transformation_data = 0,
  .interpolation_is_identity = 1,

  .num_sub_elements = 0,
  .sub_elements = NULL
};

// End of code for element element_f550351ae4ab454688402d27a041f1dc22f0a82d

// Code for dofmap dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165



void tabulate_entity_dofs_dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165 =
{
  .signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 1)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165

// Code for dofmap dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5

ufc_dofmap* sub_dofmaps_dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5[3] = { &dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165, &dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165, &dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165 };

void tabulate_entity_dofs_dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5 =
{
  .signature = "FFCX dofmap for VectorElement(FiniteElement('Lagrange', tetrahedron, 1), dim=3)",
  .block_size = 3,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 4,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 0,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5,
  .num_sub_dofmaps = 3,
  .sub_dofmaps = sub_dofmaps_dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5
};

// End of code for dofmap dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5

// Code for dofmap dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d



void tabulate_entity_dofs_dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d(int* restrict dofs, int d, int i)
{
switch (d)
{
case 0:
    switch (i)
    {
    case 0:
        dofs[0] = 0;
        break;
    case 1:
        dofs[0] = 1;
        break;
    case 2:
        dofs[0] = 2;
        break;
    case 3:
        dofs[0] = 3;
        break;
    }
    break;
case 1:
    switch (i)
    {
    case 0:
        dofs[0] = 4;
        break;
    case 1:
        dofs[0] = 5;
        break;
    case 2:
        dofs[0] = 6;
        break;
    case 3:
        dofs[0] = 7;
        break;
    case 4:
        dofs[0] = 8;
        break;
    case 5:
        dofs[0] = 9;
        break;
    }
    break;
}
}

ufc_dofmap dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d =
{
  .signature = "FFCX dofmap for FiniteElement('Lagrange', tetrahedron, 2)",
  .block_size = 1,
  .num_global_support_dofs = 0,
  .num_element_support_dofs = 10,
  .num_entity_dofs[0] = 1,
  .num_entity_dofs[1] = 1,
  .num_entity_dofs[2] = 0,
  .num_entity_dofs[3] = 0,
  .tabulate_entity_dofs = tabulate_entity_dofs_dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d,
  .num_sub_dofmaps = 0,
  .sub_dofmaps = NULL
};

// End of code for dofmap dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d

// Code for integral integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7

void tabulate_tensor_integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7(ufc_scalar_t* restrict A,
                                    const ufc_scalar_t* restrict w,
                                    const ufc_scalar_t* restrict c,
                                    const double* restrict coordinate_dofs,
                                    const int* restrict entity_local_index,
                                    const uint8_t* restrict quadrature_permutation,
                                    const uint32_t cell_permutation)
{
    // Quadrature rules
    static const double weights_929[15] = { 0.03028367809708918, 0.006026785714285717, 0.006026785714285717, 0.006026785714285717, 0.006026785714285717, 0.01164524908602897, 0.01164524908602897, 0.01164524908602897, 0.01164524908602897, 0.01094914156138645, 0.01094914156138645, 0.01094914156138645, 0.01094914156138645, 0.01094914156138645, 0.01094914156138645 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [permutation][entities][points][dofs]
    static const double FE11_C0_Q929[1][1][15][10] =
        { { { { -0.125, -0.125, -0.125, -0.125, 0.25, 0.25, 0.2499999999999999, 0.2500000000000001, 0.2499999999999999, 0.2499999999999999 },
              { -0.1111111111111112, 0.0, -0.1111111111111111, -0.1111111111111111, 0.4444444444444445, 0.0, 0.0, 0.4444444444444445, 0.4444444444444445, 0.0 },
              { 0.0, -0.1111111111111112, -0.1111111111111111, -0.1111111111111111, 0.4444444444444445, 0.4444444444444445, 0.4444444444444444, 0.0, 0.0, 0.0 },
              { -0.1111111111111112, -0.1111111111111111, -0.1111111111111111, 0.0, 0.0, 0.0, 0.4444444444444444, 0.0, 0.4444444444444444, 0.4444444444444444 },
              { -0.1111111111111112, -0.1111111111111112, 0.0, -0.1111111111111111, 0.0, 0.4444444444444445, 0.0, 0.4444444444444445, 0.0, 0.4444444444444445 },
              { -0.07438016528925623, 0.3305785123966942, -0.0743801652892562, -0.07438016528925616, 0.03305785123966944, 0.2644628099173553, 0.2644628099173553, 0.03305785123966944, 0.03305785123966945, 0.2644628099173554 },
              { 0.3305785123966942, -0.07438016528925621, -0.07438016528925623, -0.07438016528925613, 0.03305785123966948, 0.03305785123966945, 0.03305785123966946, 0.2644628099173554, 0.2644628099173553, 0.2644628099173552 },
              { -0.07438016528925624, -0.07438016528925624, -0.07438016528925621, 0.3305785123966942, 0.2644628099173555, 0.2644628099173555, 0.03305785123966941, 0.2644628099173555, 0.03305785123966942, 0.03305785123966939 },
              { -0.07438016528925624, -0.07438016528925624, 0.3305785123966942, -0.07438016528925614, 0.2644628099173554, 0.03305785123966949, 0.2644628099173554, 0.03305785123966945, 0.2644628099173554, 0.03305785123966939 },
              { -0.05769230769230774, -0.05769230769230773, -0.05769230769230765, -0.05769230769230765, 0.01771569176271328, 0.1153846153846154, 0.1153846153846153, 0.1153846153846154, 0.1153846153846153, 0.7515150774680559 },
              { -0.05769230769230779, -0.05769230769230773, -0.05769230769230765, -0.05769230769230764, 0.1153846153846153, 0.01771569176271319, 0.1153846153846153, 0.1153846153846153, 0.7515150774680558, 0.1153846153846153 },
              { -0.05769230769230781, -0.05769230769230772, -0.05769230769230767, -0.05769230769230764, 0.1153846153846154, 0.1153846153846155, 0.01771569176271326, 0.7515150774680561, 0.1153846153846153, 0.1153846153846154 },
              { -0.05769230769230771, -0.05769230769230772, -0.05769230769230769, -0.05769230769230765, 0.751515077468056, 0.1153846153846155, 0.1153846153846154, 0.1153846153846154, 0.1153846153846154, 0.01771569176271322 },
              { -0.0576923076923077, -0.05769230769230774, -0.05769230769230767, -0.05769230769230765, 0.1153846153846154, 0.7515150774680561, 0.1153846153846153, 0.1153846153846154, 0.01771569176271323, 0.1153846153846154 },
              { -0.0576923076923077, -0.05769230769230772, -0.05769230769230771, -0.05769230769230765, 0.1153846153846153, 0.1153846153846154, 0.751515077468056, 0.01771569176271334, 0.1153846153846154, 0.1153846153846154 } } } };
    static const double FE9_C0_D001_Q929[1][1][1][4] = { { { { -1.0, 0.0, 0.0, 1.0 } } } };
    static const double FE9_C0_D010_Q929[1][1][1][3] = { { { { -1.0, 0.0, 1.0 } } } };
    static const double FE9_C0_D100_Q929[1][1][1][2] = { { { { -1.0, 1.0 } } } };
    // Quadrature loop independent computations for quadrature rule 929
    const double J_c0 = coordinate_dofs[0] * FE9_C0_D100_Q929[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D100_Q929[0][0][0][1];
    const double J_c4 = coordinate_dofs[1] * FE9_C0_D010_Q929[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D010_Q929[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D010_Q929[0][0][0][2];
    const double J_c8 = coordinate_dofs[2] * FE9_C0_D001_Q929[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D001_Q929[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D001_Q929[0][0][0][2] + coordinate_dofs[11] * FE9_C0_D001_Q929[0][0][0][3];
    const double J_c5 = coordinate_dofs[1] * FE9_C0_D001_Q929[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D001_Q929[0][0][0][1] + coordinate_dofs[7] * FE9_C0_D001_Q929[0][0][0][2] + coordinate_dofs[10] * FE9_C0_D001_Q929[0][0][0][3];
    const double J_c7 = coordinate_dofs[2] * FE9_C0_D010_Q929[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D010_Q929[0][0][0][1] + coordinate_dofs[8] * FE9_C0_D010_Q929[0][0][0][2];
    const double J_c1 = coordinate_dofs[0] * FE9_C0_D010_Q929[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D010_Q929[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D010_Q929[0][0][0][2];
    const double J_c6 = coordinate_dofs[2] * FE9_C0_D100_Q929[0][0][0][0] + coordinate_dofs[5] * FE9_C0_D100_Q929[0][0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE9_C0_D100_Q929[0][0][0][0] + coordinate_dofs[4] * FE9_C0_D100_Q929[0][0][0][1];
    const double J_c2 = coordinate_dofs[0] * FE9_C0_D001_Q929[0][0][0][0] + coordinate_dofs[3] * FE9_C0_D001_Q929[0][0][0][1] + coordinate_dofs[6] * FE9_C0_D001_Q929[0][0][0][2] + coordinate_dofs[9] * FE9_C0_D001_Q929[0][0][0][3];
    ufc_scalar_t sp_929[15];
    sp_929[0] = J_c4 * J_c8;
    sp_929[1] = J_c5 * J_c7;
    sp_929[2] = sp_929[0] + -1 * sp_929[1];
    sp_929[3] = J_c0 * sp_929[2];
    sp_929[4] = J_c5 * J_c6;
    sp_929[5] = J_c3 * J_c8;
    sp_929[6] = sp_929[4] + -1 * sp_929[5];
    sp_929[7] = J_c1 * sp_929[6];
    sp_929[8] = sp_929[3] + sp_929[7];
    sp_929[9] = J_c3 * J_c7;
    sp_929[10] = J_c4 * J_c6;
    sp_929[11] = sp_929[9] + -1 * sp_929[10];
    sp_929[12] = J_c2 * sp_929[11];
    sp_929[13] = sp_929[8] + sp_929[12];
    sp_929[14] = fabs(sp_929[13]);
    for (int iq = 0; iq < 15; ++iq)
    {
        const ufc_scalar_t fw0 = sp_929[14] * weights_929[iq];
        for (int i = 0; i < 10; ++i)
            for (int j = 0; j < 10; ++j)
                A[10 * i + j] += fw0 * FE11_C0_Q929[0][0][iq][i] * FE11_C0_Q929[0][0][iq][j];
    }
}



ufc_integral integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7 =
{
  .enabled_coefficients = NULL,
  .tabulate_tensor = tabulate_tensor_integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7,
  .needs_transformation_data = 0
};

// End of code for integral integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7

// Code for form form_b8193ca8b9cfcc5e94913f4471eb75300da525f7


ufc_dofmap* dofmaps_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7[2] = { &dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d, &dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d };
ufc_finite_element* finite_elements_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7[2] = { &element_f550351ae4ab454688402d27a041f1dc22f0a82d, &element_f550351ae4ab454688402d27a041f1dc22f0a82d };

// Return a list of the coefficient names.
const char** coefficient_name_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7(void)
{
return NULL;
}

// Return a list of the constant names.
const char** constant_name_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7(void)
{
return NULL;
}

int* integral_ids_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7(ufc_integral_type integral_type)
{
static int integral_ids_cell_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7[1] = { -1 };
switch (integral_type)
{
case cell:
    return integral_ids_cell_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7;
default:
    return NULL;
}
}

int num_integrals_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7(ufc_integral_type integral_type)
{
switch (integral_type)
{
case cell:
    return 1;
case interior_facet:
    return 0;
case exterior_facet:
    return 0;
default:
    return 0;
}
}

ufc_integral** integrals_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7(ufc_integral_type integral_type)
{
static ufc_integral* integrals_cell_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7[1] = { &integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7 };
switch (integral_type)
{
case cell:
    return integrals_cell_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7;
default:
    return NULL;
}
}

ufc_form form_b8193ca8b9cfcc5e94913f4471eb75300da525f7 =
{

  .signature = "8a944509e6f8714070d9a8b51ef6c0dde5930b8e077bc36254ff2931209e9ff3f56e9ab6cef88bdffd85a2543ef1277ae7d07362062f02ce8bc0cd64a88dd545",
  .rank = 2,
  .num_coefficients = 0,
  .num_constants = 0,
  .original_coefficient_position = NULL,

  .coefficient_name_map = coefficient_name_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,
  .constant_name_map = constant_name_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,

  .finite_elements = finite_elements_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,
  .dofmaps = dofmaps_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,

  .integral_ids = integral_ids_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,
  .num_integrals = num_integrals_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7,

  .integrals = integrals_form_b8193ca8b9cfcc5e94913f4471eb75300da525f7
};

// Alias name
ufc_form* form_mass_a = &form_b8193ca8b9cfcc5e94913f4471eb75300da525f7;

ufc_function_space* functionspace_form_mass_a(const char* function_name)
{
static ufc_function_space functionspace_v =
{
.finite_element = &element_f550351ae4ab454688402d27a041f1dc22f0a82d,
.dofmap = &dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
static ufc_function_space functionspace_u =
{
.finite_element = &element_f550351ae4ab454688402d27a041f1dc22f0a82d,
.dofmap = &dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d,
.geometry_family = "Lagrange",
.geometry_degree = 1
};
if (strcmp(function_name, "v") == 0)
    return &functionspace_v;
else if (strcmp(function_name, "u") == 0)
    return &functionspace_u;
return NULL;

}

// End of code for form form_b8193ca8b9cfcc5e94913f4471eb75300da525f7
