// This code conforms with the UFC specification version 2018.2.0.dev0
// and was automatically generated by FFCX version 2019.2.0.dev0.
//
// This code was generated with the following parameters:
//
//  {'assume_aligned': -1,
//   'epsilon': 1e-14,
//   'output_directory': '.',
//   'padlen': 1,
//   'profile': False,
//   'scalar_type': 'double',
//   'table_atol': 1e-09,
//   'table_rtol': 1e-06,
//   'tabulate_tensor_void': False,
//   'ufl_file': ['mass.ufl'],
//   'verbosity': 30,
//   'visualise': False}


#pragma once

typedef double ufc_scalar_t;
#include <ufc.h>

#ifdef __cplusplus
extern "C" {
#endif

extern ufc_finite_element element_7bc5d8db1633d2838f6877f08d8c9f1689ca8165;

extern ufc_finite_element element_bdceac99366b2920d64d0754bdb3a21263af46d5;

extern ufc_finite_element element_f550351ae4ab454688402d27a041f1dc22f0a82d;

extern ufc_dofmap dofmap_7bc5d8db1633d2838f6877f08d8c9f1689ca8165;

extern ufc_dofmap dofmap_bdceac99366b2920d64d0754bdb3a21263af46d5;

extern ufc_dofmap dofmap_f550351ae4ab454688402d27a041f1dc22f0a82d;

extern ufc_integral integral_cell_otherwise_b8193ca8b9cfcc5e94913f4471eb75300da525f7;

extern ufc_form form_b8193ca8b9cfcc5e94913f4471eb75300da525f7;

// Helper used to create form using name which was given to the
// form in the UFL file.
// This helper is called in user c++ code.
//
extern ufc_form* form_mass_a;

// Helper used to create function space using function name
// i.e. name of the Python variable.
//
ufc_function_space* functionspace_form_mass_a(const char* function_name);

#ifdef __cplusplus
}
#endif
