name: Test custom assemblers

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-20.04
    container: dolfinx/dolfinx

    steps:
      - uses: actions/checkout@v2

      - name: flake8 code
        run: flake8 .

      - name: Run tests
        run: |
          cd tests
          python3 -m pytest test_mass_matrix.py

     - name: Run demos
       run: | 
         cd demos
         python3 mass_matrix.py
