name: Test Python assemblers

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-20.04

    container: dolfinx/dev-env:v0.5.0

    strategy:
      matrix:
        petsc_mode: [real, complex]
        petsc_int_type: [32, 64]
        CXX: [c++, clang++]
        CC: [cc, clang]
        exclude:
          - CC: cc
            CXX: clang++
          - CC: clang
            CXX: c++

    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      HDF5_MPI: "ON"
      HDF5_DIR: "/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
      PETSC_ARCH: linux-gnu-${{ matrix.petsc_mode }}-${{ matrix.petsc_int_type }}
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
      CXX_FLAGS: "-Wall -Werror -g -pedantic -Ofast -march=native"

    steps:
      - uses: actions/checkout@v2

      - name: Install meshio/h5py
        run: |
          CC=mpicc pip3 install --no-cache-dir --no-binary=h5py h5py meshio
      - name: Get Basix and install
        uses: actions/checkout@v2
        with:
          path: ./basix
          repository: FEniCS/basix
          ref: v0.5.0

      - name: Install FEniCS Python components (dolfinx)
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build-basix -S ./basix/cpp
          cmake --build build-basix
          cmake --install build-basix
          python3 -m pip install ./basix/python
          python3 -m pip install git+https://github.com/FEniCS/ufl.git@2022.2.0
          python3 -m pip install git+https://github.com/FEniCS/ffcx.git@v0.5.0
      - name: Install dolfinx
        uses: actions/checkout@v2
        with:
          path: ./dolfinx
          repository: FEniCS/dolfinx
          ref: v0.5.0

      - name: Configure C++ (dolfinx)
        run: cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -B build-dolfinx -S ./dolfinx/cpp/

      - name: Build and install C++ library (dolfinx)
        run: |
          cmake --build build-dolfinx
          cmake --install build-dolfinx
      - name: Build Python interface (dolfinx)
        run: python3 -m pip -v install ./dolfinx/python/

      - name: Install custom assemblers (C++)
        run: |
          cmake -G Ninja -B build-dir -DCMAKE_BUILD_TYPE=Developer  -DCMAKE_CXX_FLAGS="${CXX_FLAGS}"  cpp/
          ninja -C build-dir install

      - name: Install custom assemblers
        run: BUILD_TYPE=Debug CXXFLAGS=${CXX_FLAGS} python3 -m pip -v install python/

      - name: Flake8 code
        run:  |
          cd python
          flake8 . --exclude=build
          cd ..

      - name: Run tests
        run: |
          cd python/tests
          python3 -m pytest . -vs

      - name: Run demos
        run: |
          cd python/demos
          python3 mass_matrix.py
          python3 stiffness_matrix.py
